export const LOCALSTORAGE_KEY = Object.freeze({
  SERVICE_GROUP_UUID: 'STRATO_SG_UUID',
  SERVICE_GROUP_NAME: 'STRATO_SG_NAME',
  PROJECT: 'STRATO_INFRA_PROJECT', // project
  PER_PAGES: 'STRATO_PER_PAGES',
})

export const SESSIONSTORAGE_KEY = Object.freeze({
  STRATO_SERVICE_MENUS: 'STRATO_SERVICE_MENUS',
  STRATO_INFRA_MENU: 'STRATO_INFRA_MENU',
  STRATO_INFRA_MENU_FLAT: 'STRATO_INFRA_MENU_FLAT',
  STRATO_TENANT_SELECTABLE: 'STRATO_TENANT_SELECTABLE',
})

export const TOKEN_KEY = Object.freeze({
  LOCAL_ACCESS: 'local_access_token',
  LOCAL_REFRESH: 'local_refresh_token',
})
